name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install numpy scipy matplotlib sympy pandas

      # Step 5: Create results directory
      - name: Create results folder
        run: mkdir -p static/results

      # Step 6: Run the Python script
      - name: Run signal processing script
        run: |
          python -c "
import sys
from pathlib import Path
sys.path.insert(0, '.')
from your_script_name import process_signal, symbolic_transforms

# Test symbolic transforms
lap, four = symbolic_transforms('sin(t)')
print('Laplace:', lap)
print('Fourier:', four)

# Test signal processing
results = process_signal('synthetic')
print('Generated files:', list(results.keys()))
"
